"""
efta.model.fitting
==================
Two fitting functions for reaction-based models:

:func:`model`
    Mathematical fitting — free parameters are log-transformed to ensure
    positivity.  Uses ``scipy.optimize.least_squares`` (residual-based).

:func:`model_chem`
    Chemical fitting — supports continuous ranges ``(a, b)`` and discrete
    sets ``[a, b, c]`` per parameter.  Uses differential evolution for global
    search followed by local polishing.

Both functions accept a user-defined callable *func* that takes the free
parameters and returns a :class:`~efta.reaction.reaction` or
:class:`~efta.reactions.reactions` object.  The optimiser calls
``.equilibrium(initial_point, maintain=maintain)`` internally.
"""

from __future__ import annotations

import inspect
import warnings
from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
from scipy.optimize import least_squares, differential_evolution

from ..errors import InputError, ConvergenceError
from .mass_action import mass_action_residuals, is_data_sufficient


def _constraints_to_acceptable(func) -> dict:
    """
    Convert stored constraints on *func* to ``acceptable_*`` kwargs for
    ``_model_chem``.  Unconstrained params default to ``(0, inf)``.
    """
    constraints = getattr(func, 'constraints', {})
    names       = _param_names(func)
    result      = {}
    for name in names:
        spec = constraints.get(name, (0, float('inf')))
        result[f'acceptable_{name}'] = spec
    return result


def _infer_method(func) -> str:
    """Infer 'cont' or 'ranged' from stored constraints on *func*."""
    constraints = getattr(func, 'constraints', {})
    for spec in constraints.values():
        if isinstance(spec, list):
            return 'ranged'
        if isinstance(spec, tuple) and spec != (0, float('inf')):
            return 'ranged'
    return 'cont' 

__all__ = ['model', 'analyze', 'montecarlo', 'Model']   # _model/_model_chem/_montecarlo* are private


# ---------------------------------------------------------------------------
# Parametric key resolution
# ---------------------------------------------------------------------------
# Data dicts (equilibrium / initial) may contain keys with $(xN) or $(expr)
# placeholders — the same notation used in freaction templates.  These are
# resolved against the current parameter values before each residual
# evaluation so that the species name in the data dict matches the species
# name generated by func(*params).
#
# Examples:
#   'LaCl$(3-x2)[$(x2)+]'  with x2=1  →  'LaCl2[+]'
#   'ML3(HL)$(2*x1-3)(org)' with x1=3 →  'ML3(HL)3(org)'
#
# After substitution the resolved key is normalised through efta's species()
# function so that e.g. '[1+]' is canonicalised to '[+]'.


import re as _re

_KEY_SAFE_NS = {'__builtins__': {}, 'abs': abs, 'round': round,
                'int': int, 'float': float}


def _is_parametric_key(key: str) -> bool:
    """Return True if *key* contains any $(expr) placeholder."""
    return '$(' in key


def _resolve_one_key(key: str, mapping: Dict[int, float]) -> str:
    """Evaluate all $(expr) in *key* using *mapping* {index: value}."""
    from ..species import _find_dollar, _eval_dollar, species as _normalise
    from ..model.freaction import _clean_species
    import re as _re

    result = []
    pos = 0
    while True:
        hit = _find_dollar(key, pos)
        if hit is None:
            result.append(key[pos:])
            break
        result.append(key[pos:hit[0]])
        expr   = hit[2]
        filled = _re.sub(r'x(\d+)',
                         lambda m: str(mapping[int(m.group(1))]),
                         expr)
        try:
            val = float(eval(filled, _KEY_SAFE_NS, {}))
        except Exception as e:
            raise ValueError(
                f"Could not evaluate parametric key expression $({expr!r}): {e}")
        # integer → plain, float → $(n)
        if val == int(val):
            result.append(str(int(val)))
        else:
            result.append(f'$({val:.6g})')
        pos = hit[1]

    raw = ''.join(result)
    # apply same simplification as _build_reaction: drop count-1, drop count-0
    cleaned = _clean_species(raw)
    return _normalise(cleaned)


def _resolve_parametric_keys(data_dict: dict, params) -> dict:
    """
    Return a copy of *data_dict* with any parametric species-name keys
    resolved against the current *params* (positional sequence, 1-indexed
    as x1, x2, …).

    Non-parametric keys are passed through unchanged.  If no key is
    parametric the original dict is returned as-is (zero allocation).

    Results are cached by (param_tuple, keys_tuple) so repeated calls
    with the same params and same dict structure are free.
    """
    if not any(_is_parametric_key(k) for k in data_dict):
        return data_dict                           # fast path: no parametric keys

    # cache key: rounded params + ordered keys of this dict
    cache_key = (tuple(round(float(v), 10) for v in params),
                 tuple(data_dict.keys()))
    cached = _resolve_cache.get(cache_key)
    if cached is not None:
        # rebuild with original values (same keys, same order)
        return {new_k: data_dict[old_k]
                for old_k, new_k in zip(data_dict.keys(), cached)}

    mapping = {i + 1: float(v) for i, v in enumerate(params)}
    resolved_keys = tuple(
        _resolve_one_key(k, mapping) if _is_parametric_key(k) else k
        for k in data_dict.keys()
    )
    _resolve_cache[cache_key] = resolved_keys
    return dict(zip(resolved_keys, data_dict.values()))

# module-level cache for resolved parametric keys
_resolve_cache: dict = {}


# ---------------------------------------------------------------------------
# Result object
# ---------------------------------------------------------------------------

class Model:
    """
    Result of a fitting run.

    Attributes
    ----------
    popt : tuple
        Optimal parameter values in the same order as *func*'s arguments.
    residuals : np.ndarray
        Final residual vector (computed - observed) / observed.
    mse : float
        Mean squared error of normalised residuals.
    rms : float
        Root-mean-square of normalised residuals (= sqrt(mse)).
    success : bool
        Whether the optimiser converged.
    message : str
        Optimiser status message.
    n_iter : int
        Number of function evaluations.
    param_names : list of str
        Parameter names from *func*'s signature.
    """

    def __init__(self, popt, residuals, success, message, n_iter, param_names):
        self.popt        = tuple(popt)
        self.residuals   = np.asarray(residuals)
        self.mse         = float(np.mean(self.residuals ** 2))
        self.rms         = float(np.sqrt(self.mse))
        self.success     = bool(success)
        self.message     = str(message)
        self.n_iter      = int(n_iter)
        self.param_names = list(param_names)

    def __repr__(self) -> str:
        params = ', '.join(f'{n}={v:.4g}'
                           for n, v in zip(self.param_names, self.popt))
        return (f"Model({params}, mse={self.mse:.3e}, rms={self.rms:.3e}, "
                f"success={self.success}, n_iter={self.n_iter})")

    def __str__(self) -> str:
        lines = ['Model']
        lines.append(f"  success  : {self.success}  ({self.message})")
        lines.append(f"  mse      : {self.mse:.4e}")
        lines.append(f"  rms      : {self.rms:.4e}")
        lines.append(f"  n_iter   : {self.n_iter}")
        lines.append("  parameters:")
        for n, v in zip(self.param_names, self.popt):
            lines.append(f"    {n:<12s} = {v:.6g}")
        return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _param_names(func) -> List[str]:
    """Return the parameter names of *func* (excluding 'self').
    
    Handles freaction/freactions objects via their .param_names property,
    and regular callables via inspect.signature.
    """
    if hasattr(func, 'param_names'):
        return list(func.param_names)
    sig = inspect.signature(func)
    return [p for p in sig.parameters if p != 'self']


def _check_fast_path(func, initials, equilibria, n_params):
    """
    Pre-check which data points can use the fast mass-action path.
    Returns a list of bools, one per data point.
    """
    flags = []
    try:
        rxn_sys_test = func(*([1.0] * n_params))
        for i in range(len(initials)):
            flags.append(
                is_data_sufficient(rxn_sys_test, equilibria[i], initials[i])
            )
    except Exception:
        flags = [False] * len(initials)
    return flags


def _build_objective(func, initials, equilibria, maintain, eq_species, v_oa=1.0):
    """
    Return a residual function ``residuals(params) -> np.ndarray``.

    Primary path (fast): direct mass-action law residuals
        r_j = log(K_j) - Σᵢ νᵢⱼ · log(aᵢ)
    evaluated directly from observed equilibrium concentrations.
    No equilibrium solver call needed — analytic and orders of magnitude faster.

    Fallback path (slow): black-box equilibrium solver, used when data is
    insufficient to evaluate mass-action directly.
    """
    n_points  = len(initials)
    n_params  = len(eq_species)   # rough proxy; refined below
    fast_path = None   # lazily initialised on first call

    # Detect parametric stoichiometry: $(xN) or $(expr) in species-name keys.
    # When present, species names change with params so the fast-path cache
    # must be rebuilt every call (stale flags cause wrong residuals or crashes).
    _parametric_stoich = any(
        '$(' in k
        for d in list(equilibria) + list(initials)
        for k in d
    )

    def _residuals(params):
        nonlocal fast_path
        res = []

        # Build reaction once per param set — cached in freaction._rxn_cache
        try:
            rxn_sys_sample = func(*params)
        except Exception:
            return np.array([1e6] * max(len(eq_species), 1) * n_points, dtype=float)

        # Cache fast_path by reaction stoich fingerprint so we don't call
        # is_data_sufficient 17× per evaluation when stoichiometry is parametric.
        stoich_key = tuple(sorted(
            rxn_sys_sample._stoich.items() if hasattr(rxn_sys_sample, '_stoich')
            else ((r._stoich.items() if hasattr(r, '_stoich') else ()) for r in getattr(rxn_sys_sample, '_reactions', []))
        ))
        if fast_path is None or (_parametric_stoich and stoich_key != _residuals._last_stoich_key):
            sample_ceq = _resolve_parametric_keys(equilibria[0], params)
            sample_c0  = _resolve_parametric_keys(initials[0],   params)
            fast_path = [
                is_data_sufficient(rxn_sys_sample,
                                   _resolve_parametric_keys(equilibria[j], params),
                                   _resolve_parametric_keys(initials[j],   params))
                for j in range(n_points)
            ]
            _residuals._last_stoich_key = stoich_key

        for i in range(n_points):
            try:
                rxn_sys = func(*params)
            except Exception:
                res.extend([1e6] * max(len(eq_species), 1))
                continue

            ceq_i = _resolve_parametric_keys(equilibria[i], params)
            c0_i  = _resolve_parametric_keys(initials[i],   params)

            if fast_path[i]:
                # ── fast path: direct mass-action residuals ───────────────
                try:
                    r = mass_action_residuals(rxn_sys, ceq_i, c0_i, v_oa=v_oa)
                    res.extend(r.tolist())
                except Exception:
                    res.extend([1e6] * max(len(eq_species), 1))
            else:
                # ── fallback: black-box equilibrium solver ────────────────
                c0 = c0_i if c0_i else ceq_i
                try:
                    ceq = rxn_sys.equilibrium(c0, maintain=maintain,
                                              v_oa=v_oa if v_oa != 1.0 else None)
                except Exception:
                    res.extend([1e6] * len(eq_species))
                    continue
                for sp in eq_species:
                    obs = equilibria[i].get(sp, 0.0)
                    got = ceq.get(sp, 0.0)
                    if obs != 0.0:
                        res.append((got - obs) / obs)
                    else:
                        res.append(got)
        return np.array(res, dtype=float)

    _residuals._last_stoich_key = None
    return _residuals




def _validate_data(initial: dict, equilibrium: dict) -> Tuple[List[dict], List[dict]]:
    """
    Accept either single-point dicts or dict-of-lists and normalise to
    lists of dicts.
    """
    # detect dict-of-lists vs single dict
    def _is_dict_of_lists(d):
        return d and all(isinstance(v, (list, np.ndarray)) for v in d.values())

    if _is_dict_of_lists(initial):
        n = len(next(iter(initial.values())))
        initials = [{sp: float(v[i]) for sp, v in initial.items()}
                    for i in range(n)]
    else:
        initials = [initial]

    if _is_dict_of_lists(equilibrium):
        n = len(next(iter(equilibrium.values())))
        equilibria = [{sp: float(v[i]) for sp, v in equilibrium.items()}
                      for i in range(n)]
    else:
        equilibria = [equilibrium]

    if len(initials) != len(equilibria):
        raise InputError(
            f"initial and equilibrium must have the same number of data points, "
            f"got {len(initials)} and {len(equilibria)}.")

    return initials, equilibria


# ---------------------------------------------------------------------------
# model — mathematical fitting
# ---------------------------------------------------------------------------

def _model(func: Callable,
          equilibrium: dict,
          initial: dict = None,
          maintain: list = None,
          *,
          x0: dict = None,
          tolerance: float = 1e-8,
          max_iter: int = 1000,
          v_oa: float = 1.0,
          solver_kw: dict = None) -> Model:
    """
    Mathematical fitting of a reaction model.

    Parameters are log-transformed internally to ensure positivity.
    Uses ``scipy.optimize.least_squares`` with the Trust Region Reflective
    method.

    Parameters
    ----------
    func : callable
        A function ``func(*params) -> reaction | reactions``.
        Parameter names are inferred from the function signature.
    equilibrium : dict
        Observed equilibrium concentrations.
        Either ``{species: value}`` (single point) or
        ``{species: [v1, v2, ...]}`` (multiple points).
    initial : dict, optional
        Initial concentrations. Same format as *equilibrium*.
        If ``None``, the observed equilibrium concentrations are used as
        the initial condition (self-consistency fitting).
    maintain : list of str, optional
        Species held fixed during equilibrium solving.
    x0 : dict, optional
        Initial guess ``{param_name: value}``.  Defaults to 1.0 for all.
    tolerance : float, optional
        Convergence tolerance for the optimiser.
    max_iter : int, optional
        Maximum number of function evaluations.
    solver_kw : dict, optional
        Extra keyword arguments forwarded to ``scipy.optimize.least_squares``.

    Returns
    -------
    Model

    Examples
    --------
    >>> def f(K):
    ...     return reaction('A = B', K)
    >>> result = model(f, equilibrium={'B': [0.04, 0.08]})
    >>> result = model(f, equilibrium={'B': [0.04, 0.08]},
    ...                initial={'A': [0.1, 0.2]})
    >>> result.popt   # (K_opt,)
    """
    maintain   = maintain or []
    solver_kw  = solver_kw or {}
    names      = _param_names(func)
    if initial is None:
        initial = equilibrium
    initials, equilibria = _validate_data(initial, equilibrium)
    eq_species = sorted({sp for eq in equilibria for sp in eq})

    # initial guess in direct space (not log)
    if x0 is None:
        x0_arr = np.ones(len(names))
    else:
        x0_arr = np.array([float(x0.get(n, 1.0)) for n in names])

        residuals_fn = _build_objective(func, initials, equilibria, maintain,
                                        eq_species, v_oa=v_oa)

    def _log_residuals(log_params):
        return residuals_fn(np.exp(log_params))

    def _log_obj_scalar(log_params):
        r = _log_residuals(log_params)
        return float(np.sum(r ** 2))

    x0_log = np.log(np.maximum(x0_arr, 1e-300))
    # Never start at exactly 0 — finite-diff step = eps*|x| = 0 when x=0.
    x0_log = np.where(x0_log == 0.0, 0.1, x0_log)

    # ── Primary: Nelder-Mead on scalar SSE ───────────────────────────────────
    # Does not rely on finite differences, works regardless of scale.
    # Initial simplex spans ±2 log-units around x0.
    from scipy.optimize import minimize
    nm_result = minimize(
        _log_obj_scalar, x0_log,
        method='Nelder-Mead',
        options={
            'maxiter':  max_iter,
            'xatol':    tolerance,
            'fatol':    tolerance,
            'initial_simplex': np.vstack([
                x0_log,
                *[x0_log + np.eye(len(names))[i] * 2.0
                  for i in range(len(names))],
            ]),
        }
    )
    best_log  = nm_result.x
    best_cost = nm_result.fun

    # ── Refine with least_squares from NM solution ───────────────────────────
    try:
        ls_result = least_squares(
            _log_residuals, best_log,
            method='lm',
            ftol=tolerance, xtol=tolerance,
            max_nfev=max_iter,
        )
        if ls_result.cost < best_cost:
            best_log  = ls_result.x
            best_cost = ls_result.cost
    except Exception:
        pass

    # make a result-like object for consistent attribute access
    class _R:
        pass
    ls_result = _R()
    ls_result.success = nm_result.success
    ls_result.message = nm_result.message
    ls_result.nfev    = int(nm_result.nfev)

    # ── Fallback: DE + polish only if least_squares genuinely failed ─────────
    # Note: rms > 0 is expected with real experimental data (measurement noise).
    # Only fall back to DE if the optimiser itself reports failure.
    if not ls_result.success:
        log_lo = np.full(len(names), -50.0)
        log_hi = np.full(len(names),  50.0)
        de_result = differential_evolution(
            _log_obj_scalar, list(zip(log_lo, log_hi)),
            seed=42, maxiter=max_iter // 5,
            tol=tolerance * 10, workers=1,
            x0=x0_log,
            **{k: v for k, v in solver_kw.items()
               if k in ('popsize', 'mutation', 'recombination', 'seed', 'workers')},
        )
        # polish DE result
        pol = least_squares(
            _log_residuals, de_result.x,
            method='trf',
            ftol=tolerance, xtol=tolerance, gtol=tolerance,
            max_nfev=max_iter,
            diff_step=0.01,
        )
        if pol.cost < best_cost:
            best_log  = pol.x
            ls_result = pol
            ls_result = type('R', (), {
                'success': pol.success or de_result.success,
                'message': pol.message,
                'nfev':    de_result.nfev + pol.nfev + ls_result.nfev,
            })()

    popt      = np.exp(best_log)
    final_res = residuals_fn(popt)

    return Model(
        popt        = popt,
        residuals   = final_res,
        success     = ls_result.success,
        message     = ls_result.message,
        n_iter      = ls_result.nfev,
        param_names = names,
    )


# ---------------------------------------------------------------------------
# model_chem — chemical fitting with constrained parameter spaces
# ---------------------------------------------------------------------------

def _neighbour_specs(gene_specs: dict, cont_params: dict) -> dict:
    """
    Build Phase-2a (exploitation) gene_specs from cont estimate.

    Discrete params → 2 nearest allowed values to cont estimate,
                      clipped to list boundaries.
    Continuous params → ±25% in log-space around cont estimate,
                        clipped to acceptable range.
                        Falls back to full range if clipped span is
                        < 10% of original log-span.
    """
    exploit_specs = {}
    for name, spec in gene_specs.items():
        v = cont_params.get(name, None)
        if v is None:
            exploit_specs[name] = spec
            continue

        if isinstance(spec, list):
            # snap to nearest 2 neighbours (or 1 if list is tiny)
            arr  = np.array(spec, dtype=float)
            diffs = np.abs(arr - float(v))
            order = np.argsort(diffs)
            n_nb  = min(2, len(arr))
            neighbours = sorted(arr[order[:n_nb]].tolist())
            exploit_specs[name] = neighbours

        else:
            lo, hi = spec
            log_lo = np.log(max(lo, 1e-300))
            log_hi = np.log(max(hi, lo * 1.001 + 1e-300))
            log_v  = np.log(max(float(v), 1e-300))

            # ±25% in log-space, clipped to [log_lo, log_hi]
            delta      = abs(log_v) * 0.25 if log_v != 0 else 1.0
            new_lo     = np.clip(log_v - delta, log_lo, log_hi)
            new_hi     = np.clip(log_v + delta, log_lo, log_hi)
            clipped_span = new_hi - new_lo

            # fallback to full range if clipped span is < 1 log-unit
            # (guarantees at least one order-of-magnitude of search space)
            if clipped_span < 1.0:
                new_lo, new_hi = log_lo, log_hi

            exploit_specs[name] = (float(np.exp(new_lo)), float(np.exp(new_hi)))

    return exploit_specs


# ---------------------------------------------------------------------------
# model_chem — chemical fitting with constrained parameter spaces
# ---------------------------------------------------------------------------

def _model_chem(func: Callable,
               equilibrium: dict,
               initial: dict = None,
               maintain: list = None,
               *,
               tolerance: float = 1e-8,
               generations: int = 100,
               sol_per_pop: int = 20,
               mating: int = 10,
               random_seed: int = 42,
               v_oa: float = 1.0,
               **param_constraints) -> Model:
    """
    Chemical fitting with per-parameter constraints.

    Three-phase strategy:

    **Phase 1 — Cont warm-up** (Nelder-Mead, ignores discrete constraints)
        Fast continuous estimate used to seed the GA.

    **Phase 2a — Exploitation** (25% generations, 50% population)
        Discrete params: 2 nearest neighbours to cont estimate.
        Continuous params: ±25% log-space window around cont estimate,
        clipped to acceptable range.

    **Phase 2b — Exploration** (75% generations, 100% population)
        Full acceptable range, full population, initialised from Phase-2a
        winner — so the search starts near the good region.
    """
    from .ga import GA

    maintain = maintain or []
    names    = _param_names(func)
    if initial is None:
        initial = equilibrium
    initials, equilibria = _validate_data(initial, equilibrium)
    eq_species = sorted({sp for eq in equilibria for sp in eq})

    # ── build gene_specs ─────────────────────────────────────────────────────
    gene_specs = {}
    for name in names:
        key  = f'acceptable_{name}'
        spec = param_constraints.get(key, (0, float('inf')))
        if isinstance(spec, (list, np.ndarray)):
            gene_specs[name] = list(spec)
        elif isinstance(spec, tuple) and len(spec) == 2:
            lo, hi = float(spec[0]), float(spec[1])
            if lo == 0 and hi == float('inf'):
                lo, hi = 1e-15, 1e15
            if lo >= hi:
                raise InputError(
                    f"acceptable_{name}: lower bound {lo} >= upper bound {hi}.")
            gene_specs[name] = (lo, hi)
        else:
            raise InputError(
                f"acceptable_{name} must be a (lo, hi) tuple or a list, "
                f"got {type(spec).__name__}.")

        residuals_fn = _build_objective(func, initials, equilibria, maintain,
                                        eq_species, v_oa=v_oa)
    total_evals  = [0]

    def fitness(params: dict):
        vals = [params[n] for n in names]
        res  = residuals_fn(vals)
        total_evals[0] += 1
        return -float(np.sum(res ** 2))

    # ── Phase 1: cont warm-up ─────────────────────────────────────────────────
    # For discrete params: seed at median of allowed list.
    # For continuous params: run Nelder-Mead for a fast estimate.
    # This avoids the unconstrained solver going to zero for discrete-like params.

    # seed discrete params at their median allowed value
    discrete_seed = {}
    for name, spec in gene_specs.items():
        if isinstance(spec, list):
            arr = sorted(spec)
            discrete_seed[name] = float(arr[len(arr) // 2])

    try:
        # Run Nelder-Mead with discrete params fixed at their median seed.
        # Wrap func to substitute discrete params before calling original func.
        if discrete_seed:
            orig_names = names

            def func_cont(*args):
                all_params = []
                cont_idx = 0
                cont_vals = list(args)
                for name in orig_names:
                    if name in discrete_seed:
                        all_params.append(discrete_seed[name])
                    else:
                        all_params.append(cont_vals[cont_idx])
                        cont_idx += 1
                return func(*all_params)

            import inspect as _inspect
            cont_only_names = [n for n in names if n not in discrete_seed]
            func_cont.__signature__ = _inspect.Signature([
                _inspect.Parameter(n, _inspect.Parameter.POSITIONAL_OR_KEYWORD)
                for n in cont_only_names
            ])
            cont_fit = _model(func_cont, equilibrium, initial=initial,
                              maintain=maintain,
                              tolerance=tolerance * 100, max_iter=500)
            cont_params = dict(discrete_seed)
            for n, v in zip(cont_only_names, cont_fit.popt):
                cont_params[n] = v
        else:
            cont_fit = _model(func, equilibrium, initial=initial,
                              maintain=maintain,
                              tolerance=tolerance * 100, max_iter=500)
            cont_params = {n: v for n, v in zip(names, cont_fit.popt)}
    except Exception:
        # fallback: median of discrete, geometric mean of continuous
        cont_params = {}
        for name, spec in gene_specs.items():
            if isinstance(spec, list):
                arr = sorted(spec)
                cont_params[name] = float(arr[len(arr) // 2])
            else:
                lo, hi = spec
                cont_params[name] = float(np.exp(
                    (np.log(max(lo,1e-300)) + np.log(max(hi,lo+1e-300))) / 2))

    # ── Phase 2a: exploitation ────────────────────────────────────────────────
    gen_exploit  = max(1, int(generations * 0.25))
    pop_exploit  = max(4, int(sol_per_pop * 0.5))
    exploit_specs = _neighbour_specs(gene_specs, cont_params)

    ga_exploit = GA(
        fitness_func  = fitness,
        gene_specs    = exploit_specs,
        generations   = gen_exploit,
        pop_size      = pop_exploit,
        n_parents     = max(2, pop_exploit // 2),
        early_stop    = -tolerance,
        seed          = random_seed,
    )
    sol_exploit = ga_exploit.run()

    # ── Phase 2b: exploration ─────────────────────────────────────────────────
    gen_explore = max(1, generations - gen_exploit)
    # seed first individual from Phase-2a winner
    ga_explore = GA(
        fitness_func  = fitness,
        gene_specs    = gene_specs,
        generations   = gen_explore,
        pop_size      = sol_per_pop,
        n_parents     = mating,
        early_stop    = -tolerance,
        seed          = random_seed + 1,
    )
    # inject Phase-2a best into initial population via custom init
    ga_explore._phase2a_seed = sol_exploit.params
    _orig_random = ga_explore.__class__.__dict__.get('run')

    # patch population initialisation to include Phase-2a seed
    from .ga import _random_individual, GA as _GA
    orig_run = ga_explore.run.__func__

    def run_with_seed(self):
        import numpy as _np
        from .ga import _random_individual, _decode_individual, _clip_individual
        rng     = _np.random.default_rng(self.seed)
        n_evals = 0

        # initialise population with Phase-2a seed in slot 0
        pop = _np.array([_random_individual(self._parsed, rng)
                         for _ in range(self.pop_size)])
        # encode seed
        seed_params = self._phase2a_seed
        for i2, (name2, kind2, spec2) in enumerate(self._parsed):
            v2 = seed_params.get(name2)
            if v2 is not None:
                if kind2 == 'continuous':
                    pop[0, i2] = _np.log(max(float(v2), 1e-300))
                else:
                    vals2 = spec2
                    idx2  = int(_np.argmin(
                        _np.abs(_np.array(vals2, dtype=float) - float(v2))))
                    pop[0, i2] = float(idx2)

        def _eval_pop(population):
            nonlocal n_evals
            scores = _np.empty(len(population))
            for j, ind in enumerate(population):
                params    = _decode_individual(ind, self._parsed)
                scores[j] = float(self.fitness_func(params))
                n_evals  += 1
            return scores

        fitness_arr = _eval_pop(pop)
        best_idx    = int(_np.argmax(fitness_arr))
        best_ind    = pop[best_idx].copy()
        best_fit    = float(fitness_arr[best_idx])
        best_gen    = 0

        for gen in range(self.generations):
            if self.early_stop is not None and best_fit >= self.early_stop:
                break
            parents   = self._select(pop, fitness_arr, rng)
            offspring = self._crossover(parents, rng)
            offspring = self._mutate(offspring, rng)
            off_fit   = _eval_pop(offspring)
            worst     = int(_np.argmin(off_fit))
            if best_fit > off_fit[worst]:
                offspring[worst] = best_ind.copy()
                off_fit[worst]   = best_fit
            pop         = offspring
            fitness_arr = off_fit
            gb          = int(_np.argmax(fitness_arr))
            if fitness_arr[gb] > best_fit:
                best_fit = float(fitness_arr[gb])
                best_ind = pop[gb].copy()
                best_gen = gen + 1

        from .ga import GASolution, _decode_individual
        return GASolution(
            params     = _decode_individual(best_ind, self._parsed),
            fitness    = best_fit,
            generation = best_gen,
            n_evals    = n_evals,
        )

    import types
    ga_explore.run = types.MethodType(run_with_seed, ga_explore)
    sol_explore = ga_explore.run()

    # ── pick best across all phases ────────────────────────────────────────────
    best_sol = sol_explore if sol_explore.fitness >= sol_exploit.fitness else sol_exploit

    popt      = [best_sol.params[n] for n in names]
    final_res = residuals_fn(popt)
    sse       = -best_sol.fitness

    return Model(
        popt        = popt,
        residuals   = final_res,
        success     = bool(sse < tolerance * 1e6),
        message     = (f"3-phase: cont+exploit({gen_exploit}gen)+explore({gen_explore}gen), "
                       f"SSE={sse:.3e}"),
        n_iter      = total_evals[0],
        param_names = names,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def model(func, equilibrium: dict,
          initial: dict = None,
          v_oa: float = 1.0,
          **kwargs) -> 'Model':
    """
    Fit free parameters of a :class:`~efta.model.freaction` or
    :class:`~efta.model.freactions` to observed equilibrium data.

    Method is auto-detected from stored constraints:

    - All params ``(0, inf)`` → ``'cont'`` (Nelder-Mead, log-transformed).
    - Any param has a list or finite range → ``'ranged'`` (pygad GA).

    Use :meth:`freaction.constrain` to set constraints.

    Parameters
    ----------
    func : freaction | freactions
        Parameterised reaction system with optional stored constraints.
    equilibrium : dict
        Observed equilibrium concentrations.
    initial : dict, optional
        Initial concentrations. If ``None``, uses *equilibrium* as c0.
    **kwargs
        For ``'cont'``: ``x0``, ``tolerance``, ``max_iter``.
        For ``'ranged'``: ``generations``, ``sol_per_pop``, ``mating``.

    Returns
    -------
    Model

    Examples
    --------
    >>> f = (freaction("$(x1)A = B, $(x2)").params(['a', 'K'])
    ...       .constrain(a=[1,2,3], K=(1e-5,1e5)))
    >>> result = model(f, eq)
    >>> result.popt         # (a_opt, K_opt)
    """
    method = _infer_method(func)
    if method == 'cont':
        return _model(func, equilibrium, initial=initial,
                      v_oa=v_oa, **kwargs)
    else:
        acceptable = _constraints_to_acceptable(func)
        acceptable.update({k: v for k, v in kwargs.items()
                           if k.startswith('acceptable_')})
        other_kw = {k: v for k, v in kwargs.items()
                    if not k.startswith('acceptable_')}
        return _model_chem(func, equilibrium, initial=initial,
                           v_oa=v_oa, **acceptable, **other_kw)


def analyze(func, equilibrium: dict,
            initial: dict = None,
            v_oa: float = 1.0,
            **kwargs) -> list:
    """
    Bootstrap model selection via repeated train/test splits.

    Method is auto-detected from stored constraints (same logic as
    :func:`model`).

    Parameters
    ----------
    func : freaction | freactions
        Parameterised reaction system with optional stored constraints.
    equilibrium : dict
        Observed equilibrium concentrations (dict of lists).
    initial : dict, optional
    **kwargs
        ``n``, ``training_points``, ``best``, ``based_on``, ``x0``,
        ``seed``, ``tolerance``, ``max_iter``,
        ``generations``, ``mating`` (ranged only).

    Returns
    -------
    list of Analyzed

    Examples
    --------
    >>> f = (freaction("$(x1)A = B, $(x2)").params(['a', 'K'])
    ...       .constrain(a=[1,2,3], K=(1e-5,1e5)))
    >>> results = analyze(f, eq, n=100)
    >>> best = results[0]
    """
    from .suggest import _suggest, _suggest_chem
    method = _infer_method(func)
    if method == 'cont':
        return _suggest(func, equilibrium, initial=initial,
                        v_oa=v_oa, **kwargs)
    else:
        acceptable = _constraints_to_acceptable(func)
        acceptable.update({k: v for k, v in kwargs.items()
                           if k.startswith('acceptable_')})
        other_kw = {k: v for k, v in kwargs.items()
                    if not k.startswith('acceptable_')}
        return _suggest_chem(func, equilibrium, initial=initial,
                             v_oa=v_oa, **acceptable, **other_kw)


# ---------------------------------------------------------------------------
# Internal Monte Carlo helpers
# ---------------------------------------------------------------------------

def _perturb(data_dict: dict, noise, rng: 'np.random.Generator') -> dict:
    """
    Return a copy of *data_dict* with each value perturbed by relative noise.

    *noise* is either a float (same for all species) or a dict
    ``{species: float}``.  Each value v is replaced by
    ``v * (1 + N(0, noise_for_species))``, clipped to a small positive floor.
    """
    out = {}
    for sp, v in data_dict.items():
        sigma = noise.get(sp, 0.05) if isinstance(noise, dict) else float(noise)
        if isinstance(v, (list, np.ndarray)):
            arr = np.asarray(v, dtype=float)
            perturbed = arr * (1.0 + rng.normal(0.0, sigma, size=arr.shape))
            out[sp] = np.maximum(perturbed, 1e-300).tolist()
        else:
            perturbed = float(v) * (1.0 + rng.normal(0.0, sigma))
            out[sp] = max(perturbed, 1e-300)
    return out


def _montecarlo(func, equilibrium, initial=None, maintain=None, *,
                noise=0.05, n=100, seed=42, training_points=0.75,
                based_on='lev', v_oa=1.0,
                x0=None, tolerance=1e-8, max_iter=1000,
                **kw):
    """
    Monte Carlo uncertainty for continuous fitting.
    Returns Analyzed with param_std and n_matched populated.
    """
    from .suggest import Analyzed, _eval_residuals, _stat_tests, _split, _subset
    import numpy as _np

    maintain = maintain or []
    rng      = _np.random.default_rng(seed)
    initials, equilibria = _validate_data(
        initial if initial is not None else equilibrium, equilibrium)
    eq_species = sorted({sp for eq in equilibria for sp in eq})
    names      = _param_names(func)
    n_points   = len(equilibria)

    all_popt   = []
    all_mse    = []
    all_mte    = []
    all_t      = []
    all_lev    = []
    all_train  = []
    all_test   = []

    for _ in range(n):
        eq_p = _perturb(_lists_to_dict(equilibria), noise, rng)
        c0_p = _perturb(_lists_to_dict(initials), noise, rng) if initial is not None else eq_p

        try:
            fit = _model(func, eq_p, initial=c0_p, maintain=maintain,
                         x0=x0, tolerance=tolerance, max_iter=max_iter, v_oa=v_oa, **kw)
        except Exception:
            continue

        init_l, eq_l = _validate_data(c0_p, eq_p)
        train_idx, test_idx = _split(n_points, training_points, rng)
        train_res = _eval_residuals(func, fit.popt, _subset(eq_l, train_idx),
                                    _subset(init_l, train_idx), eq_species, maintain)
        test_res  = _eval_residuals(func, fit.popt, _subset(eq_l, test_idx),
                                    _subset(init_l, test_idx),  eq_species, maintain)
        t_stat, t_pval, lev_stat, lev_p = _stat_tests(train_res, test_res)

        all_popt.append(fit.popt)
        all_mse.append(float(_np.mean(train_res**2)))
        all_mte.append(float(_np.mean(test_res**2)))
        all_t.append(t_pval)
        all_lev.append(lev_p)
        all_train.append(train_idx)
        all_test.append(test_idx)

    if not all_popt:
        raise RuntimeError("All Monte Carlo iterations failed.")

    _sort_key = {'lev': all_lev, 'mse': [-v for v in all_mse],
                 'mte': [-v for v in all_mte], 't': all_t}
    scores    = _sort_key.get(based_on, all_lev)
    best_idx  = int(_np.argmax(scores))
    best_popt = all_popt[best_idx]
    best_fit  = _model(func, equilibrium, initial=initial, maintain=maintain,
                       x0={nm: v for nm, v in zip(names, best_popt)},
                       tolerance=tolerance, max_iter=max_iter, v_oa=v_oa, **kw)

    dists     = {name: [p[i] for p in all_popt] for i, name in enumerate(names)}
    param_std = {name: float(_np.std(vals)) for name, vals in dists.items()}
    t_stat_b, t_pval_b, lev_stat_b, lev_p_b = _stat_tests(
        _np.array([all_mse[best_idx]]), _np.array([all_mte[best_idx]]))

    return Analyzed(
        fit          = best_fit,
        mse          = all_mse[best_idx],
        mte          = all_mte[best_idx],
        t_stat       = all_t[best_idx],
        t_pval       = all_t[best_idx],
        lev_stat     = all_lev[best_idx],
        lev_pval     = all_lev[best_idx],
        train_idx    = all_train[best_idx],
        test_idx     = all_test[best_idx],
        distributions= [dists[nm] for nm in names],
        mse_dist     = all_mse,
        mte_dist     = all_mte,
        t_dist       = all_t,
        lev_dist     = all_lev,
        param_std    = param_std,
        n_matched    = len(all_popt),
    )


def _lists_to_dict(list_of_dicts):
    if not list_of_dicts:
        return {}
    keys = list_of_dicts[0].keys()
    return {k: [d[k] for d in list_of_dicts] for k in keys}


def _montecarlo_chem(func, equilibrium, initial=None, maintain=None, *,
                     noise=0.05, n=100, seed=42, training_points=0.75,
                     based_on='lev', v_oa=1.0,
                     tolerance=1e-8, generations=100, mating=10,
                     **param_constraints):
    """
    Monte Carlo uncertainty for ranged/discrete fitting.
    Discrete params (list constraints) → filter to best stoich.
    Continuous params (tuple constraints) → param_std from filtered iterations.
    Returns Analyzed with param_std and n_matched populated.
    """
    from .suggest import Analyzed, _eval_residuals, _stat_tests, _split, _subset
    import numpy as _np

    maintain = maintain or []
    rng      = _np.random.default_rng(seed)
    initials, equilibria = _validate_data(
        initial if initial is not None else equilibrium, equilibrium)
    eq_species = sorted({sp for eq in equilibria for sp in eq})
    names      = _param_names(func)
    n_points   = len(equilibria)

    # identify discrete vs continuous params
    discrete_names   = set()
    continuous_names = set()
    for name in names:
        key = f'acceptable_{name}'
        if key in param_constraints:
            spec = param_constraints[key]
            if isinstance(spec, (list, _np.ndarray)):
                discrete_names.add(name)
            else:
                continuous_names.add(name)
        else:
            continuous_names.add(name)

    all_popt  = []
    all_mse   = []
    all_mte   = []
    all_t     = []
    all_lev   = []
    all_train = []
    all_test  = []

    for i_iter in range(n):
        eq_p = _perturb(_lists_to_dict(equilibria), noise, rng)
        c0_p = _perturb(_lists_to_dict(initials), noise, rng) if initial is not None else eq_p

        try:
            fit = _model_chem(func, eq_p, initial=c0_p, maintain=maintain,
                              tolerance=tolerance, generations=generations,
                              mating=mating, random_seed=seed + i_iter,
                              v_oa=v_oa, **param_constraints)
        except Exception:
            continue

        init_l, eq_l = _validate_data(c0_p, eq_p)
        train_idx, test_idx = _split(n_points, training_points, rng)
        train_res = _eval_residuals(func, fit.popt, _subset(eq_l, train_idx),
                                    _subset(init_l, train_idx), eq_species, maintain)
        test_res  = _eval_residuals(func, fit.popt, _subset(eq_l, test_idx),
                                    _subset(init_l, test_idx),  eq_species, maintain)
        t_stat, t_pval, lev_stat, lev_p = _stat_tests(train_res, test_res)

        all_popt.append(fit.popt)
        all_mse.append(float(_np.mean(train_res**2)))
        all_mte.append(float(_np.mean(test_res**2)))
        all_t.append(t_pval)
        all_lev.append(lev_p)
        all_train.append(train_idx)
        all_test.append(test_idx)

    if not all_popt:
        raise RuntimeError("All Monte Carlo iterations failed.")

    _sort_key = {'lev': all_lev, 'mse': [-v for v in all_mse],
                 'mte': [-v for v in all_mte], 't': all_t}
    scores    = _sort_key.get(based_on, all_lev)
    best_idx  = int(_np.argmax(scores))
    best_popt = all_popt[best_idx]

    # filter matched discrete stoich
    name_to_idx   = {name: i for i, name in enumerate(names)}
    best_discrete  = {name: best_popt[name_to_idx[name]] for name in discrete_names}
    matched = [
        popt for popt in all_popt
        if all(_np.isclose(popt[name_to_idx[name]], val, rtol=1e-6)
               for name, val in best_discrete.items())
    ] or all_popt

    dists     = {name: [p[name_to_idx[name]] for p in all_popt] for name in names}
    param_std = {name: float(_np.std([p[name_to_idx[name]] for p in matched]))
                 for name in continuous_names}

    best_fit  = _model_chem(func, equilibrium, initial=initial, maintain=maintain,
                            tolerance=tolerance, generations=max(10, generations // 10),
                            mating=mating, v_oa=v_oa, **param_constraints)

    return Analyzed(
        fit          = best_fit,
        mse          = all_mse[best_idx],
        mte          = all_mte[best_idx],
        t_stat       = all_t[best_idx],
        t_pval       = all_t[best_idx],
        lev_stat     = all_lev[best_idx],
        lev_pval     = all_lev[best_idx],
        train_idx    = all_train[best_idx],
        test_idx     = all_test[best_idx],
        distributions= [dists[nm] for nm in names],
        mse_dist     = all_mse,
        mte_dist     = all_mte,
        t_dist       = all_t,
        lev_dist     = all_lev,
        param_std    = param_std,
        n_matched    = len(matched),
    )


# ---------------------------------------------------------------------------
# Public: montecarlo()
# ---------------------------------------------------------------------------

def montecarlo(func, equilibrium: dict,
               initial: dict = None,
               *, noise=0.05, n: int = 100, seed: int = 42,
               training_points: float = 0.75,
               based_on: str = 'lev',
               v_oa: float = 1.0,
               **kwargs) -> 'Analyzed':
    """
    Monte Carlo uncertainty analysis by perturbing observed concentrations.

    Each iteration adds relative noise to equilibrium (and initial)
    concentrations, refits the model, and collects parameter values.
    The best result is selected by highest Levene p-value (most homoscedastic
    residuals).

    Method is auto-detected from stored constraints (same logic as
    :func:`model`).

    Parameters
    ----------
    func : freaction | freactions | callable
        Parameterised reaction system with optional stored constraints.
    equilibrium : dict
        Observed equilibrium concentrations.
    initial : dict, optional
        Initial concentrations.  If ``None``, uses *equilibrium* as c0.
    maintain : list, optional
        Species held fixed during equilibrium solving.
    noise : float or dict, optional
        Relative noise (1-sigma).
        ``0.05`` → 5% noise on all species (default).
        ``{'LaCl2[+]': 0.05, 'H[+]': 0.02}`` → per-species noise.
    n : int, optional
        Number of Monte Carlo iterations (default 100).
    seed : int, optional
        Random seed (default 42).
    **kwargs
        For ``method='cont'``: ``x0``, ``tolerance``, ``max_iter``.
        For ``method='ranged'``: ``acceptable_{name}``, ``generations``,
        ``sol_per_pop``, ``mating``, ``tolerance``.

    Returns
    -------
    Analyzed
        Same as :func:`analyze` but with ``param_std`` and ``n_matched``
        additionally populated.

    Examples
    --------
    >>> f = (freaction("$(x1)A = B, $(x2)").params(['a', 'K'])
    ...       .constrain(K=(1e-5, 1e5)))
    >>> result = montecarlo(f, eq, noise=0.05, n=100)
    >>> result.param_std    # {'K': 0.85}

    >>> f.constrain(a=[1,2,3])   # now ranged
    >>> result = montecarlo(f, eq, noise=0.05, n=100)
    >>> result.param_std    # {'K': 0.72}  — std from matched iterations only
    >>> result.n_matched    # e.g. 67
    """
    method = _infer_method(func)
    if method == 'cont':
        return _montecarlo(func, equilibrium, initial=initial,
                           noise=noise, n=n, seed=seed,
                           training_points=training_points,
                           based_on=based_on,
                           v_oa=v_oa, **kwargs)
    else:
        acceptable = _constraints_to_acceptable(func)
        acceptable.update({k: v for k, v in kwargs.items()
                           if k.startswith('acceptable_')})
        other_kw = {k: v for k, v in kwargs.items()
                    if not k.startswith('acceptable_')}
        return _montecarlo_chem(func, equilibrium, initial=initial,
                                noise=noise, n=n, seed=seed,
                                training_points=training_points,
                                based_on=based_on,
                                v_oa=v_oa, **acceptable, **other_kw)
